--- 
title: "Evolution of Lysogeny Supplemental Materials"
author: "Alison Cameron, Seth Dorchen, Sarah Doore, and Anya Vostinar"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: anyaevostinar/Evolution-of-Lysogeny-Paper
description: "Supplemental Materials"
---

# Introduction

This book contains all supplemental materials for the [evolution of lysogeny paper.](https://doi.org/10.32942/osf.io/3qcwk)

## About our supplemental material 

Our supplemental materials include the following:

- R scripts 

- System configuration settings 

- Graphs not included in our paper 

## Contributing Authors
- Alison Cameron
- Seth Dorchen
- Sarah Doore
- [Anya Vostinar](https://anyaevostinar.github.io/)

## Research Overview

### Abstract
Bacteriophages, also known as phages, are viruses that infect bacteria. 
They are found everywhere in nature, playing vital roles in microbiomes and bacterial evolution due to the selective pressure that they place on their hosts. 
As obligate endosymbionts, phages depend on bacteria for successful reproduction, and either destroy their hosts through lysis or are maintained within the host through lysogeny. 
Lysis involves reproduction within the host cell and ultimately results in the disruption or bursting of the cell to release phage progeny. 
Alternatively, lysogeny is the process by which phage DNA is incorporated into the host DNA or maintained alongside the host chromosome, and thus the phage reproduces when their host reproduces. 
Recent work has demonstrated that phages can exist along the parasitism-mutualism spectrum, prompting questions of how phage would evolve one reproductive strategy over the other, and in which conditions.
In this work, we present an agent-based model of bacteriophage/bacterial co-evolution that enables lysogenized phage to directly impact their host's fitness by using the software platform Symbulation.
We demonstrate that a viral population with beneficial lysogenic phage can select against lytic strategies. 
This result has implications for bottom-up control of vital ecosystems.


### Experiments
The following chapters of this book represent the main experiments conducted for our research. 
We implemented two features of focus: induction into the lytic cycle and the impact that a prophage can have on host metabolism. 
The first two experiments explore these features independently of one another (Chapter 5 being host metabolism impact only without induction and Chapter 6 being induction without any impact on host metabolism). 
The next two chapters investigate the impact of both of these features on the co-evolution of viruses and bacteria. 
Chapter 7 shows the data for the maintaining of harmful/neutral/beneficial phage populations by starting with fixed populations, while Chapter 8 shows the data for the de novo evolution of harmful/neutral/beneficial phage by starting with random populations. 
Our primary findings are shown in Chapters 5 and 6, and the following chapters will be relevant for future work.

### Results
Our results show that even in conditions that would typically select for a lytic phage population, the potential for prophage to have a positive impact on host metabolism leads to selection for more temperate populations. 
This result is primarily shown in the mean chance of lysis plot in Chapter 5. 
This result has important implications for the construction of microbiomes and thus ecosystems in general.
More dicussion of our results and their implications can be read about in [our paper.](https://doi.org/10.32942/osf.io/3qcwk)


